services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db

  react-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app  # Mount the client directory for live reload
    environment:
      - CHOKIDAR_USEPOLLING=true  # Use polling for file watching in Docker
    depends_on:
      - mongodb

  server-app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app  # Mount the server directory for live reload
    depends_on:
      - mongodb

volumes:
  mongodb_data:
